substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'license-monitor-repo'
  _IMAGE_NAME: 'license-monitor'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest',
      '.'
    ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
